export const areas = [
  { slug: 'direito-trabalhista', title: 'Direito Trabalhista', category: 'TRABALHISTA', description: 'Orientação sobre relações de trabalho, direitos e deveres de empregados e empregadores.', details: 'A análise trabalhista considera os fatos, documentos e as particularidades da relação de trabalho. Temas como jornada, verbas rescisórias, contratos e condições de trabalho exigem avaliação individualizada.', items: ['Contratos e relações de trabalho', 'Jornada e verbas trabalhistas', 'Rescisão do contrato de trabalho'] },
  { slug: 'aposentadorias', title: 'Aposentadorias', category: 'PREVIDENCIÁRIO', description: 'Análise dos requisitos e das possibilidades de aposentadoria, conforme o histórico contributivo.', details: 'As regras de aposentadoria variam conforme o histórico de contribuições e a legislação aplicável. A avaliação dos registros previdenciários ajuda a identificar requisitos, documentos e eventuais pendências.', items: ['Histórico de contribuições e CNIS', 'Regras de transição', 'Documentação para requerimento'] },
  { slug: 'revisoes-de-beneficios', title: 'Revisões de Benefícios', category: 'PREVIDENCIÁRIO', description: 'Avaliação criteriosa dos critérios de concessão e cálculo de benefícios previdenciários.', details: 'Uma revisão depende de fundamento jurídico, documentação e análise dos prazos aplicáveis. Nem todo benefício admite revisão, e a avaliação prévia é indispensável para compreender riscos e possibilidades.', items: ['Análise da carta de concessão', 'Salários e períodos de contribuição', 'Prazos e requisitos aplicáveis'] },
  { slug: 'bpc-loas', title: 'BPC/LOAS', category: 'ASSISTENCIAL', description: 'Orientação sobre o benefício assistencial e seus requisitos legais e sociais.', details: 'O Benefício de Prestação Continuada é assistencial, não uma aposentadoria. Sua análise considera os critérios legais de idade ou deficiência e a situação socioeconômica, conforme as regras vigentes.', items: ['Critérios do benefício assistencial', 'Cadastro e documentação', 'Avaliação da situação individual'] },
  { slug: 'beneficios-por-incapacidade', title: 'Benefícios por Incapacidade', category: 'PREVIDENCIÁRIO', description: 'Orientação jurídica sobre benefícios relacionados à incapacidade para o trabalho.', details: 'A concessão depende de requisitos previdenciários e avaliação da incapacidade. Documentação médica, histórico contributivo e a situação profissional são analisados individualmente, sem garantia de concessão.', items: ['Documentação médica e contributiva', 'Requerimentos e avaliações', 'Análise de decisões administrativas'] },
  { slug: 'planejamento-previdenciario', title: 'Planejamento Previdenciário', category: 'PREVIDENCIÁRIO', description: 'Estudo do histórico previdenciário para decisões conscientes sobre o futuro.', details: 'O planejamento reúne informações sobre contribuições, vínculos e objetivos pessoais. O estudo considera a legislação vigente e possíveis cenários, que podem mudar ao longo do tempo.', items: ['Organização do histórico previdenciário', 'Identificação de inconsistências', 'Estudo de cenários de aposentadoria'] },
];

export const articles = [
  { slug: 'aposentadoria-por-onde-comecar', category: 'DIREITO PREVIDENCIÁRIO', title: 'Aposentadoria: por onde começar a organizar seus documentos?', description: 'O histórico de contribuições é o ponto de partida para uma análise previdenciária.', body: ['O planejamento de um requerimento começa pela organização dos documentos pessoais e do histórico de trabalho. Carteiras de trabalho, comprovantes de contribuições e o Cadastro Nacional de Informações Sociais (CNIS) podem ajudar nessa análise.', 'É importante conferir se os vínculos e contribuições estão registrados corretamente. Divergências e períodos ausentes podem exigir documentação complementar.', 'As regras aplicáveis dependem da situação individual. Este conteúdo é informativo e não substitui análise jurídica do caso concreto.'] },
  { slug: 'rescisao-do-contrato-de-trabalho', category: 'DIREITO TRABALHISTA', title: 'Rescisão do contrato: a importância de uma análise cuidadosa.', description: 'Conhecer documentos e circunstâncias ajuda a compreender o encerramento do vínculo.', body: ['O encerramento de uma relação de trabalho pode envolver diferentes modalidades de rescisão. Os direitos e deveres variam conforme o contrato, os fatos e a forma de desligamento.', 'Termo de rescisão, contrato de trabalho, comprovantes de pagamento e registros de jornada são exemplos de documentos que podem contribuir para a análise.', 'A avaliação individualizada permite compreender dúvidas sobre os valores e procedimentos aplicáveis. Não há conclusão automática sem conhecimento do caso.'] },
  { slug: 'entendendo-bpc-loas', category: 'BENEFÍCIOS ASSISTENCIAIS', title: 'BPC/LOAS: benefício assistencial não é aposentadoria.', description: 'Entenda a natureza do benefício e a importância de avaliar seus requisitos.', body: ['O BPC é um benefício de natureza assistencial previsto na legislação brasileira. Ele não se confunde com uma aposentadoria e possui critérios próprios.', 'A avaliação envolve requisitos legais, condições socioeconômicas e, conforme o caso, aspectos relacionados à deficiência ou à idade. Cadastros e documentação atualizados são importantes.', 'A existência de um diagnóstico ou de determinada condição pessoal, isoladamente, não permite concluir pela concessão. É necessária análise dos requisitos aplicáveis.'] },
];