import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, ArrowDown, MapPin } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { pageHead, site } from '@/config/site';
import { AboutSection, AreasSection, PrinciplesSection, TeamSection, ArticlesSection, LocationSection } from '@/components/site/sections';
import { ContactForm } from '@/components/site/contact-form';
import architecture from '@/assets/architecture.jpg';
export const Route = createFileRoute('/')({head:()=>pageHead('Advocacia em Dracena SP','Orientação jurídica trabalhista e previdenciária em Dracena, SP, com atenção individualizada, ética e responsabilidade.','/'),component:Index});
function Index(){return <><section className="hero"><img className="hero-image" src={architecture} alt="Arquitetura institucional contemporânea — imagem conceitual, não representa a fachada do escritório" width={1920} height={1088} fetchPriority="high"/><div className="hero-overlay"/><div className="container hero-content"><span className="eyebrow hero-eyebrow"><span/>{site.signature.toUpperCase()}</span><h1>Seus direitos merecem<br className="desktop-break"/> atenção, respeito<br className="desktop-break"/> e <em>compromisso.</em></h1><p>Atuação jurídica nas áreas trabalhista e previdenciária, com orientação individualizada, responsabilidade profissional e clareza em cada etapa.</p><div className="hero-actions"><Button asChild className="gold-button"><Link to="/areas-de-atuacao">CONHEÇA NOSSA ATUAÇÃO <ArrowRight/></Link></Button><Button asChild variant="outline" className="light-outline"><Link to="/contato">FALE COM O ESCRITÓRIO <ArrowUpRightIcon/></Link></Button></div></div><div className="hero-bottom container"><span><MapPin size={14}/> DRACENA, SÃO PAULO</span><a href="#escritorio-inicio" aria-label="Ver apresentação do escritório"><ArrowDown size={17}/></a><span className="image-caption">IMAGEM ARQUITETÔNICA CONCEITUAL</span></div></section><div id="escritorio-inicio"><AboutSection/></div><AreasSection/><PrinciplesSection/><TeamSection/><ArticlesSection/><LocationSection/><section className="section contact-home"><div className="container contact-grid"><div><span className="eyebrow">CONTATO</span><h2>Estamos aqui<br/>para ouvir você.</h2><p>Um espaço para iniciar uma conversa com atenção, respeito e discrição.</p><Link to="/contato" className="text-link">Página de contato <ArrowRight size={17}/></Link></div><ContactForm/></div></section></>;}
function ArrowUpRightIcon(){return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M7 17 17 7M7 7h10v10"/></svg>;}
