import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Scale, FileText, HeartHandshake, Landmark, ShieldCheck, Compass, MapPin, ArrowRight, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { areas, articles } from '@/lib/content';
import { site, directionsUrl } from '@/config/site';
import architecture from '@/assets/architecture.jpg';

export function SectionHeading({ eyebrow, title, children }: { eyebrow: string; title: string; children?: React.ReactNode }) {
 return <div className="section-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{children}</div>;
}
export function AboutSection() { return <section className="section about-section"><div className="container about-grid"><figure className="architecture-detail"><img src={architecture} alt="Arquitetura contemporânea — imagem conceitual" width={1920} height={1088} loading="lazy"/><figcaption>ARQUITETURA INSTITUCIONAL · IMAGEM CONCEITUAL</figcaption></figure><div><SectionHeading eyebrow="O ESCRITÓRIO" title="Uma atuação jurídica orientada pela ética e pela responsabilidade."/><p>O cuidado começa pela escuta. Cada trajetória tem suas particularidades e merece uma análise criteriosa, com atenção ao que realmente importa.</p><p>Atuação nas áreas trabalhista e previdenciária, com orientação individualizada, comunicação clara e responsabilidade profissional em cada etapa.</p><Link className="text-link" to="/escritorio">Conheça o escritório <ArrowUpRight size={17}/></Link></div></div></section>; }
const icons = [Scale, Landmark, FileText, HeartHandshake, ShieldCheck, Compass];
export function AreasSection({ full = false }: { full?: boolean }) { return <section className="section areas-section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="ÁREAS DE ATUAÇÃO" title="Conhecimento jurídico. Atenção à sua realidade."/>{!full && <Link className="text-link" to="/areas-de-atuacao">Todas as áreas <ArrowUpRight size={17}/></Link>}</div><div className="areas-grid">{areas.map((area,i) => { const Icon = icons[i]; return <Link key={area.slug} to="/areas-de-atuacao/$slug" params={{slug:area.slug}} className="area-card"><div className="card-top">{Icon && <Icon size={29} strokeWidth={1.15}/>}<span>0{i+1}</span></div><h3>{area.title}</h3><p>{area.description}</p><span className="card-link">SAIBA MAIS <ArrowUpRight size={16}/></span></Link>; })}</div></div></section>; }
export function PrinciplesSection() { return <section className="principles-section"><div className="container"><SectionHeading eyebrow="O QUE NOS ORIENTA" title="Princípios que conduzem cada decisão."/><div className="principles-grid">{[['Ética profissional','Respeito às normas da profissão e à confiança depositada.'],['Responsabilidade','Análise criteriosa e compromisso com a orientação jurídica.'],['Transparência','Comunicação clara sobre as etapas e os limites de cada caso.'],['Atenção individualizada','Escuta atenta e respeito à singularidade de cada trajetória.']].map(([title,text],i)=><div key={title}><span className="principle-number">0{i+1}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>; }
export function TeamSection({ full = false }: { full?: boolean }) { return <section className="section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="PROFISSIONAIS" title="Pessoas. Compromisso. Confiança."/>{!full && <Link className="text-link" to="/equipe">Nossa equipe <ArrowUpRight size={17}/></Link>}</div><div className="team-grid">{site.professionals.map(person=><article className="team-card" key={person.name}><div className="portrait-placeholder">{person.photo ? <img src={person.photo} alt={person.name} loading="lazy"/> : <><UserRound size={45} strokeWidth={0.8}/><span>FOTOGRAFIA PROFISSIONAL A INSERIR</span></>}</div><h3>{person.name}</h3>{person.oab && <p>{person.oab}</p>}{person.biography && <p>{person.biography}</p>}</article>)}</div>{full && <p className="small-note">Fotografias, registros profissionais e biografias serão apresentados após confirmação dos dados oficiais.</p>}</div></section>; }
export function ArticlesSection({full = false}: {full?: boolean}) { return <section className="section articles-section"><div className="container"><div className="heading-row"><SectionHeading eyebrow="CONTEÚDOS JURÍDICOS" title="Informação para compreender seus direitos."/>{!full && <Link className="text-link" to="/conteudos">Todos os conteúdos <ArrowUpRight size={17}/></Link>}</div><div className="articles-grid">{articles.map((article,i)=><Link to="/conteudos/$slug" params={{slug:article.slug}} key={article.slug} className="article-card"><div className={`article-art article-art-${i}`}><span>0{i+1}</span>{i===0 ? <Landmark size={72} strokeWidth={0.65}/> : i===1 ? <Scale size={72} strokeWidth={0.65}/> : <HeartHandshake size={72} strokeWidth={0.65}/>}</div><span className="eyebrow">{article.category}</span><h3>{article.title}</h3><p>{article.description}</p><span className="text-link">Ler conteúdo <ArrowUpRight size={17}/></span></Link>)}</div></div></section>; }
export function LocationSection() { return <section className="section location-section"><div className="container location-grid"><div><SectionHeading eyebrow="LOCALIZAÇÃO" title="Em Dracena, perto de você."/><div className="address-line"><MapPin size={21}/><p>{site.address}<br/>{site.city}</p></div><Button asChild className="gold-button"><a href={directionsUrl} target="_blank" rel="noopener noreferrer">COMO CHEGAR <ArrowUpRight/></a></Button></div><iframe className="map-frame" title="Localização do endereço em Dracena no Google Maps" loading="lazy" referrerPolicy="no-referrer" src={`https://maps.google.com/maps?q=${encodeURIComponent(site.fullAddress)}&output=embed`}/></div></section>; }
export function ContactBanner() { return <section className="contact-banner"><div className="container"><div><span className="eyebrow">VAMOS CONVERSAR</span><h2>Uma orientação cuidadosa<br/>começa com uma boa conversa.</h2></div><Button asChild className="gold-button"><Link to="/contato">FALE COM O ESCRITÓRIO <ArrowRight/></Link></Button></div></section>; }
export function PageIntro({eyebrow,title,description}: {eyebrow:string;title:string;description:string}) {return <section className="page-intro"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>;}
