import { Link, useRouterState } from '@tanstack/react-router';
import { useState, useEffect } from 'react';
import { Menu, X, ArrowUpRight, MessageCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { site, whatsappUrl } from '@/config/site';
export function Header() {
 const [scrolled,setScrolled] = useState(false); const [open,setOpen] = useState(false);
 const path=useRouterState({select:s=>s.location.pathname});
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>30);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update);},[]);
 useEffect(()=>setOpen(false),[path]);
 useEffect(()=>{if(!open)return; const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open]);
 return <><a className="skip-link" href="#main">Ir para o conteúdo</a><header className={`site-header ${scrolled||path!=='/'||open?'solid':''}`}><div className="header-inner"><Link to="/" className="brand" aria-label={`${site.name} — Início`}><span className="monogram">L<span>A</span></span><span className="brand-name">{site.name.toUpperCase()}<small>ADVOCACIA</small></span></Link><nav className="desktop-nav" aria-label="Navegação principal">{site.navigation.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:true}} activeProps={{className:'active'}}>{item.label}</Link>)}</nav><Button asChild className="header-contact gold-button"><Link to="/contato">ENTRE EM CONTATO <ArrowUpRight/></Link></Button><Button variant="ghost" size="icon" className="mobile-toggle" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} aria-controls="mobile-menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav id="mobile-menu" className="mobile-nav" aria-label="Navegação móvel">{site.navigation.map(item=><Link key={item.to} to={item.to}>{item.label}<ArrowUpRight size={18}/></Link>)}</nav>}</header></>;
}
export function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-grid"><div><p className="footer-name">{site.name}</p><p>{site.signature}</p><p className="footer-address">{site.address}<br/>{site.city}</p></div><nav aria-label="Navegação do rodapé">{site.navigation.slice(1).map(item=><Link key={item.to} to={item.to}>{item.label}</Link>)}</nav><div><span className="eyebrow">INFORMAÇÃO E RESPONSABILIDADE</span><p>Este site possui finalidade exclusivamente informativa. As informações apresentadas não substituem orientação jurídica individualizada.</p><Link to="/politica-de-privacidade" className="privacy-link">Política de privacidade <ArrowUpRight size={14}/></Link></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {site.name}</span><span>Denominação provisória para apresentação institucional.</span></div></div></footer>;}
export function WhatsApp(){const url=whatsappUrl(site.whatsapp,site.whatsappEnabled);if(!url)return null;return <Button asChild className="whatsapp-button" size="icon"><a href={url} target="_blank" rel="noopener noreferrer" aria-label="Contato por WhatsApp"><MessageCircle/></a></Button>;}
